[default.general]
chip = "RP2040"
log_level = "INFO"
# RP2040 does not support connect_under_reset
connect_under_reset = false

[default.rtt]
enabled = true
up_channels = [{ channel = 0, up_mode = "NoBlockSkip", format = "Defmt" }]
timeout = 3000
